services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    privileged: true
    restart: unless-stopped
    ports:
      - 2080:8080
    volumes:
      - /:/rootfs:ro
      - /sys:/sys:ro
      - /var/run:/var/run:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    ports:
    - 2090:9090
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    volumes:
    - /mnt/ssd/Apps/Prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
    - cadvisor
  
  grafana:
    image: grafana/grafana
    environment: 
      GF_SECURITY_DISABLE_INITIAL_ADMIN_CREATION: "true"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
      GF_AUTH_DISABLE_SIGNOUT_MENU: "true"
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
    ports:
      - "2000:3000"
    depends_on:
      - prometheus
networks: {}
