# Temporary SSL Certificate Setup with Cloudflare DNS Challenge
# This compose file generates wildcard SSL certificates using Cloudflare DNS challenge
# No need for a temporary nginx server since DNS challenge doesn't require HTTP validation

services:
  # SSL Certificate generation using Cloudflare DNS challenge
  certbot-setup:
    image: certbot/dns-cloudflare
    container_name: certbot-setup
    volumes:
      - ./certbot/conf:/etc/letsencrypt
    environment:
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
    entrypoint: ""
    command: >
      sh -c "
      echo 'Creating Cloudflare credentials file...' &&
      echo 'dns_cloudflare_api_token = ${CLOUDFLARE_API_TOKEN}' > /etc/letsencrypt/cloudflare.ini &&
      chmod 600 /etc/letsencrypt/cloudflare.ini &&
      echo 'Generating wildcard SSL certificate for *.minh-nguyen.tech...' &&
      certbot certonly --dns-cloudflare --dns-cloudflare-credentials /etc/letsencrypt/cloudflare.ini --email ${LETSENCRYPT_EMAIL} -d '*.minh-nguyen.tech' -d 'minh-nguyen.tech' --agree-tos --non-interactive &&
      echo 'Wildcard SSL certificate generated successfully!'
      "
