services:
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
      - ./nginx/logs:/var/log/nginx
    networks:
      - proxy-network
    depends_on:
      - wireguard

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email ${LETSENCRYPT_EMAIL} -d ${PRIMARY_DOMAIN} --agree-tos

  certbot-renew:
    image: certbot/certbot
    container_name: certbot-renew
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: sh -c "while :; do sleep 12h; certbot renew --quiet; done"
    restart: unless-stopped

  wireguard:
    image: linuxserver/wireguard:latest
    container_name: wireguard
    network_mode: host
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=${WG_PUID}
      - PGID=${WG_PGID}
      - TZ=${WG_TZ}
      - SERVERURL=auto
      - SERVERPORT=${WG_SERVERPORT}
      - PEERS=${WG_PEERS}
      - PEERDNS=auto
      - INTERNAL_SUBNET=${WG_INTERNAL_SUBNET}
      - ALLOWEDIPS=${WG_INTERNAL_SUBNET}
    volumes:
      - ./wireguard/config:/config
      - /lib/modules:/lib/modules
    restart: unless-stopped

networks:
  proxy-network:
    driver: bridge